### ISSUE TITLE
Block don't render properly with chisel blocks

### ISSUE THREAD

**Issue by JoeMBlair** [AbrarSyed/SecretRoomsMod-forge#244] opened 2018-04-05 19:32 UTC
**Optifine?**: No
**Mods**: Chisel 0.2.0.31, SecretRoomsMod 5.6.0

The blocks don't seem to render properly when secret door is placed on chisel blocks. It seems to only happen on chisel blocks.

![2018-04-05_20 20 06](https://user-images.githubusercontent.com/5678349/38387673-84ded1ba-3910-11e8-991c-0ad899554ac2.png)

**Comment by Wyn-Price** [comment] 2018-04-05 20:56
I won't be able to do anything about it for a month or 2. I have exams coming up and I can't really look into it. I'll look through chisel code and see if I can figure out why but I can promise anything

**Comment by Wyn-Price** [comment] 2018-04-12 00:59
I couldnt reproduce this. Could you tell me what mods you where using?

**Comment by JoeMBlair** [comment] 2018-04-12 07:05
Just chisel, secretroomsmod and conntected textures dependency. Would using java 8 64 bit or using java arguments affect it?

**Comment by Wyn-Price** [comment] 2018-04-12 11:31
No. I've managed to reproduce this issue and i think I know whats causing it. Its because of the way chisel models work, I can go around this though, but im not sure how easily

**Comment by Wyn-Price** [comment] 2018-04-13 17:41
This should be fixed in 5.6.2

**Closed** 2018-04-30 13:16 UTC
Labels: Other Mod Compatibility
