### ISSUE TITLE
[Startup crash]MalisisDoors compat problem

### ISSUE THREAD

**Issue by apheliotropism** [AbrarSyed/SecretRoomsMod-forge#160] opened 2015-01-04 15:21 UTC
malisisCore-1.7.10-0.10.3
malisisDoors-1.7.10-1.3.3
secret rooms-1.7.10-4.7.1.377

there is crash report, http://pastebin.com/FCXWdJkc

**Comment by justin2108** [comment] 2015-01-13 11:00
Got the same problem.
Java Version: 1.7.0_45
MCP v9.05 
FML v7.10.85.1286 
Minecraft Forge 10.13.2.1286
secretroomsmod-1.7.10-4.7.1.379.jar

Optifine disabled

**Comment by AbrarSyed** [comment] 2015-01-13 17:12
should be fixed now. try the latest version of the SecretRoomsMod from the fileserver.
http://files.minecraftforge.net/SecretRoomsMod/

**Comment by mattymaats** [comment] 2015-01-19 19:32
This issue isn't closed FYI

Using 
secretroomsmod-1.7.10-4.7.1.379 
malisiscore-1.7.10-0.10.5
malisisdoors-1.7.10-1.4.2

Reference to this contribution
https://github.com/Ordinastie/MalisisDoors/issues/18

---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 1/19/15 12:23 PM
Description: Exception in server tick loop

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: com/github/abrarsyed/secretroomsmod/malisisdoors/CamoDoorRenderer
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:162)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:515)
	at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:88)
	at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:319)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:170)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:620)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoClassDefFoundError: com/github/abrarsyed/secretroomsmod/malisisdoors/CamoDoorRenderer
	at com.github.abrarsyed.secretroomsmod.malisisdoors.MalisisDoorsCompat.preInit(MalisisDoorsCompat.java:82)
	at com.github.abrarsyed.secretroomsmod.common.SecretRooms.preLoad(SecretRooms.java:149)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:513)
	... 5 more
Caused by: java.lang.ClassNotFoundException: com.github.abrarsyed.secretroomsmod.malisisdoors.CamoDoorRenderer
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	... 33 more
Caused by: java.lang.NoClassDefFoundError: net/malisis/doors/door/renderer/DoorRenderer
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 35 more
Caused by: java.lang.ClassNotFoundException: net.malisis.doors.door.renderer.DoorRenderer
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	... 39 more

**Comment by AbrarSyed** [comment] 2015-01-19 20:07
@Ordinastie 
poke?

**Comment by LemADEC** [comment] 2015-01-19 20:54
Also, SecretRooms mod won't load anymore if MalicisDoors mod isn't installed.

**Comment by Parker8283** [comment] 2015-01-19 21:31
I'm getting this crash only on the dedi-server.

**Comment by mattymaats** [comment] 2015-01-20 13:02
@AbrarSyed I had to roll the server back to 

malisiscore-1.7.10-0.10.3
malisisdoors-1.7.10-1.3.2
secretroomsmod-1.7.10-4.7.1.376

It worked on single player but as soon as I put it onto the server it dungoofed with the error I put above. If you need me to test anything for you let me know.

**Comment by AbrarSyed** [comment] 2015-01-20 16:05
fixed by #162  thanks again @Ordinastie 
Should be showing up on the files pae as build #390 any minute now.

**Closed by AbrarSyed** 2015-01-20 16:05 UTC

**Comment by LemADEC** [comment] 2015-01-20 19:53
I guess you meant build #380 :)
