### ISSUE TITLE
Secret Iron Door Server Crash

### ISSUE THREAD

**Issue by SirWilli** [AbrarSyed/SecretRoomsMod-forge#156] opened 2014-12-04 22:10 UTC
Version: secretroomsmod-1.7.10-4.7.1.376

Just placed a secret iron door and the server crashed:
```
java.lang.IllegalArgumentException: TileEntity data is NULL!
	at com.github.abrarsyed.secretroomsmod.network.PacketCamo.<init>(PacketCamo.java:43)
	at com.github.abrarsyed.secretroomsmod.blocks.TileEntityCamo.func_145844_m(TileEntityCamo.java:84)
	at net.minecraft.entity.player.EntityPlayerMP.func_147097_b(EntityPlayerMP.java:699)
	at net.minecraft.entity.player.EntityPlayerMP.func_70071_h_(EntityPlayerMP.java:374)
	at net.minecraft.world.World.func_72866_a(World.java:2647)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:838)
	at net.minecraft.world.World.func_72870_g(World.java:2600)
	at net.minecraft.world.World.func_72939_s(World.java:2412)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:669)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:943)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at com.github.abrarsyed.secretroomsmod.network.PacketCamo.<init>(PacketCamo.java:43)
	at com.github.abrarsyed.secretroomsmod.blocks.TileEntityCamo.func_145844_m(TileEntityCamo.java:84)
	at net.minecraft.entity.player.EntityPlayerMP.func_147097_b(EntityPlayerMP.java:699)
	at net.minecraft.entity.player.EntityPlayerMP.func_70071_h_(EntityPlayerMP.java:374)
	at net.minecraft.world.World.func_72866_a(World.java:2647)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:838)
	at net.minecraft.world.World.func_72870_g(World.java:2600)

-- Entity being ticked --
Details:
	Entity Type: null (micdoodle8.mods.galacticraft.core.entities.player.GCEntityPlayerMP)
	Entity ID: 40035
	Entity Name: SirWilli
	Entity's Exact location: 2236.80, 68.00, -3851.04
	Entity's Block location: World: (2236,68,-3852), Chunk: (at 12,4,4 in 139,-241; contains blocks 2224,0,-3856 to 2239,255,-3841), Region: (4,-8; contains chunks 128,-256 to 159,-225, blocks 2048,0,-4096 to 2559,255,-3585)
	Entity's Momentum: 0.00, -0.08, 0.00
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:2412)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:669)
```

**Comment by AbrarSyed** [comment] 2015-02-05 06:10
duplicate of #153

**Closed by AbrarSyed** 2015-02-05 06:10 UTC
