### ISSUE TITLE
Connected textures not working with Optfine Fancy Connected Textures enabled

### ISSUE THREAD

**Issue by kibmcz** [AbrarSyed/SecretRoomsMod-forge#204] opened 2017-11-26 04:11 UTC
Version: 5.1.6 (Originally discovered on 5.1.5 )
Config changes: force_ambient_occlusion set to true

With the Optifine fancy connected textures enabled secret doors, one way glass (possibly others) don't blend in with select block textures (confirmed on sandstone and smooth sandstone).

Also possibly related on back side of one way glass the textures don't connect cleanly like vanilla MC glass blocks with Optifine fancy connected textures enabled.

**Comment by Wyn-Price** [comment] 2017-11-26 04:15
Connecting the glass like vanilla glass would require alot of work and would mean I need to use optifine as a requirement. Could you post a screenshot of 2 blocks (1 secret rooms one not) before and after turning on fancy textures. Also.make sure to tell me which ones which

**Comment by kibmcz** [comment] 2017-11-26 05:08
Wasn't able to show with just 2 but i made it clear which was the one way glass in the shots.
![fancy-ctm_off](https://user-images.githubusercontent.com/857986/33237304-42ffb4c2-d235-11e7-8fc5-4725a623b3d7.png)
![fancy-ctm_on](https://user-images.githubusercontent.com/857986/33237305-432ae106-d235-11e7-9f25-ada174c78ec6.png)

As per the connected glass requiring optfine shouldn't be issue  as long as its only active when fancy CTM is enabled.

**Comment by Wyn-Price** [comment] 2017-11-26 11:40
Ah right I see what's happening. I can try and fix this but optifines code isn't open source (I don't think) so figuring out how to get this to work may he difficult

**Comment by Wyn-Price** [comment] 2017-11-29 10:19
Ok looking into it more, it seems like this is an issue with Optifine. Im not sure if its even going to be considered an issue, as it only happens in specific situations like this

**Comment by Wyn-Price** [comment] 2017-11-30 14:14
Ok I found out why its happening. Gonna do some messing around with the code tonight and see if I was change anything. I have an idea on what to do tho.

**Comment by kibmcz** [comment] 2017-12-01 07:18
Ok cool... been following things (including other thread). If you want me to test something before release id be willing to.

**Comment by Wyn-Price** [comment] 2017-12-01 08:02
Yes that would be helpful. I'll send you a version when I get home from school. There might be some bugs and crashes as always but it should work

**Comment by Wyn-Price** [comment] 2017-12-02 20:03
Sorry for not doing this faster. I have school stuff coming up and Im revising for that

**Comment by kibmcz** [comment] 2017-12-03 11:20
That's totally fair as your education comes first. Knowing that its being worked on is enough no rush :)

**Comment by Wyn-Price** [comment] 2017-12-03 18:49
Could you test this .jar. I think ive sorted it out but optifine dosnt run in the dev enviroment so i havent had the chance to test

**Comment by Wyn-Price** [comment] 2017-12-03 18:49
[secretroomsmod-5.1.10.zip](https://github.com/AbrarSyed/SecretRoomsMod-forge/files/1525045/secretroomsmod-5.1.10.zip)

**Comment by kibmcz** [comment] 2017-12-03 19:57
Just tested and the front side connected textures are doing same thing and the one way glass on back side isn't rendering properly.

![2017-12-03_13 54 07](https://user-images.githubusercontent.com/857986/33529134-d4ef0106-d831-11e7-9857-50649caf2b20.png)

![2017-12-03_13 54 18](https://user-images.githubusercontent.com/857986/33529135-d95c49d8-d831-11e7-9a74-a570e2320cd7.png)

**Comment by Wyn-Price** [comment] 2017-12-03 20:00
With the bottem layer of sandstone, Im not sure theres any way to fix this. Ill check in with @sp614x but I dont think itll work. As for the other sides... what even...

**Comment by Wyn-Price** [comment] 2017-12-03 20:41
It looks like an issue with Optifine. Theres nothing I dont think i can do to solve this, so i unfortunatly might just have to drop it. Ill wait on @sp614x though

**Comment by Wyn-Price** [comment] 2017-12-09 23:11
Ok ive managed to use some reflect hackery to hijack the Optifine texturing and stuff like that. the UV issues are still there, but if you use blocks like ghost block, the blocks around it and its own block will change texture. All i need to do is to mess around with the rendering of my blocks and it should work. Im not fully confident about the version, so ill give it to you and hopfully you can mess around with it and find the bugs.

**Comment by kibmcz** [comment] 2017-12-10 06:40
That progress sounds good ill be ready for testing the next test build.

**Comment by Wyn-Price** [comment] 2017-12-10 20:02
![image](https://user-images.githubusercontent.com/15876682/33808861-083fd5e0-dde5-11e7-8801-cb9a2b0d006e.png)
nearly done :)

**Comment by Wyn-Price** [comment] 2017-12-10 20:04
the glass textures on the glass wont be able to connect. I can only choose to make it so the front connects, or the glass, and i think the front would be better as it would make it blend in more

**Comment by kibmcz** [comment] 2017-12-10 21:48
That fully makes sense as that goes with the primary goal of blending.

**Comment by Wyn-Price** [comment] 2017-12-10 22:27
could you test the mod link [here](https://github.com/AbrarSyed/SecretRoomsMod-forge/files/1546138/secretroomsmod-1.12.2-5.1.10.zip). Theres probally going to be alot of issues and stuff like that. Secret Glass currently stop blocks next to it from rendering, and secret doors dont have the door structure. Theres also some pretty funky things that happen when the block isnt a full block, or the helmet of true sight is on. If you find any bugs, even if Ive mentioned them could you report it in this thread.

**Comment by kibmcz** [comment] 2017-12-11 05:57
Took bit longer than planned but got to testing that build and well confirmed the door issue which also effects trap doors.  I wasn't really sure on a few of the things to check them out tho.. secret glass block stopping block rendering beside it, slab issue or helmet of true sight issue.

I expanded my connected texture test in this batch and it seems it connects textures with block to left and right of it but down down from SRM block even if the block lower is another SRM block. 

![sandstone basic test](https://user-images.githubusercontent.com/857986/33812557-ec122180-dde3-11e7-88da-f02e641e07e2.png)
![srm mixed test](https://user-images.githubusercontent.com/857986/33812565-f4c67920-dde3-11e7-9380-849bde519c81.png)
![single double stack connected](https://user-images.githubusercontent.com/857986/33817120-60b8ee3c-de03-11e7-849d-faa827c50358.png)

**Comment by Wyn-Price** [comment] 2017-12-11 15:22
Alright I know how to potentially solve this. I'm still in school right now but I should be home in like a couple of hours

**Comment by Wyn-Price** [comment] 2017-12-11 21:17
are you avalivle to test ? theres no bugs I could really find but im sure theres some
[secretroomsmod-1.12.2-5.1.10.zip](https://github.com/AbrarSyed/SecretRoomsMod-forge/files/1549410/secretroomsmod-1.12.2-5.1.10.zip)

**Comment by kibmcz** [comment] 2017-12-11 22:47
Out right now but will test when I get home.

**Comment by kibmcz** [comment] 2017-12-12 02:32
Just finished testing based on my currently laid out tests and found a few things: 

1. Possibly related to the fixing of the secret doors? removing and replacing the secret wood button and iron door seemed to sort that out.
![srm missing blocks](https://user-images.githubusercontent.com/857986/33864316-b947d866-deb1-11e7-94a9-7a119b34aa0e.png)

2. Seems its trying to overlay the sandstone over the  redstone lamp as part of the ctm.
![srm mixed test 2](https://user-images.githubusercontent.com/857986/33864375-fef24ab8-deb1-11e7-84e2-4fe33e3d1e50.png)

3. CTM is still not connecting on the bottom sandstone in the test set
![sandstone basic test 2](https://user-images.githubusercontent.com/857986/33864457-51db3366-deb2-11e7-9335-72ee5aea1eed.png)
![srm mixed test 2](https://user-images.githubusercontent.com/857986/33864463-56f7380e-deb2-11e7-9b8f-d3b879943213.png)

**Comment by Wyn-Price** [comment] 2017-12-12 08:01
Ah I'm an idiot. I forgot to tell you, go into the config and turn on optifine support

**Comment by kibmcz** [comment] 2017-12-12 08:53
With optifine_support set to true it crashes game when I try to load my test world.

Here are the logs:
ambient_occlusion=false
[crash-force_ambient_occlusion-false.txt](https://github.com/AbrarSyed/SecretRoomsMod-forge/files/1550811/crash-force_ambient_occlusion-false.txt)

ambient_occlusion=true
[crash-force_ambient_occlusion-true.txt](https://github.com/AbrarSyed/SecretRoomsMod-forge/files/1550813/crash-force_ambient_occlusion-true.txt)

**Comment by Wyn-Price** [comment] 2017-12-12 10:30
I'll look when I get home. When you create a new world, do these problems still happen ?

**Comment by kibmcz** [comment] 2017-12-12 10:33
Yes it crashes with same crash log output on new world creation.

**Comment by Wyn-Price** [comment] 2017-12-12 10:36
Ok I see whats happening. I'm in school for the next 5 hours but I can fix it then

**Comment by Wyn-Price** [comment] 2017-12-12 15:27
OK im at home. Im looking into it now

**Comment by Wyn-Price** [comment] 2017-12-12 15:36
Ok heres somthing strange. OptiFine_1.12.2_HD_U_C6 works but not OptiFine_1.12.2_HD_U_C7. Im looking into it now

**Comment by Wyn-Price** [comment] 2017-12-12 15:56
Somehow i managed to figure out whats going on. sp614x set a value to be final, but I can easily get around this

**Comment by Wyn-Price** [comment] 2017-12-12 16:41
theres nothing I can do untill he releases the sources. Would you be able to use Optifnie C6.

**Comment by Wyn-Price** [comment] 2017-12-12 16:46
would you be able to test this on optifine version C6? 
[secretroomsmod-1.12.2-5.1.10.zip](https://github.com/AbrarSyed/SecretRoomsMod-forge/files/1552515/secretroomsmod-1.12.2-5.1.10.zip)

**Comment by kibmcz** [comment] 2017-12-12 21:23
Hmm still crashes on C6 (I went to C7 due to Tesselating block model crashes in the past).

Here is the log: [crash-c6.txt](https://github.com/AbrarSyed/SecretRoomsMod-forge/files/1553344/crash-c6.txt)

**Comment by Wyn-Price** [comment] 2017-12-12 21:35
What version of forge are you using ?

**Comment by kibmcz** [comment] 2017-12-12 21:36
Due to requirements for some mods in main mod set 1.12.2-14.23.1.2555.

**Comment by Wyn-Price** [comment] 2017-12-12 21:38
Would you be able to do some testing ? If you could use [secretroomsmod-1.12.2-5.1.10.zip](https://github.com/AbrarSyed/SecretRoomsMod-forge/files/1553384/secretroomsmod-1.12.2-5.1.10.zip) and send me the fml-client-latest.log

**Comment by kibmcz** [comment] 2017-12-12 21:40
Here's the requested log file:
[fml-client-latest.log](https://github.com/AbrarSyed/SecretRoomsMod-forge/files/1553393/fml-client-latest.log)

**Comment by Wyn-Price** [comment] 2017-12-12 21:44
Could you do the same to [this](https://github.com/AbrarSyed/SecretRoomsMod-forge/files/1553411/secretroomsmod-1.12.2-5.1.10.zip). Thanks again

**Comment by kibmcz** [comment] 2017-12-12 21:49
OK didn't crash this time :)

First off the log:  [fml-client-latest.log](https://github.com/AbrarSyed/SecretRoomsMod-forge/files/1553416/fml-client-latest.log)

Also secret wooden button and secret doors are rendering as invisible.
![2017-12-12_15 47 25](https://user-images.githubusercontent.com/857986/33910326-fdf82252-df53-11e7-934c-c5a6d6beb7d4.png)

**Comment by Wyn-Price** [comment] 2017-12-12 21:51
does that happen when you replace them? Secret buttons are from the exact same class as ghost blocks and 1 block simple things like that so idk how it could break. Doors however could break. Would you be able to send the fml-client-latest-junk.log as well

**Comment by kibmcz** [comment] 2017-12-12 21:59
Breaking the blocks then placing them back and saving then reloading the save they render as visible but the doors are back to the previous broken state where you can't tell if they are open or closed.

As per log you mean this one? 
[fml-junk-earlystartup.log](https://github.com/AbrarSyed/SecretRoomsMod-forge/files/1553442/fml-junk-earlystartup.log)

**Comment by Wyn-Price** [comment] 2017-12-12 22:00
ah yes I did mean that sorry. is the one way glass working like it should and are the doors being rendered as full blocks or as no blocks ?

**Comment by kibmcz** [comment] 2017-12-12 22:04
The one way glass is is not working correctly as it is rendering as the sandstone full block on both sides. The doors are physical working as they should opening and closing (and can go through while they are open) but are rendering as full blocks not changing visible state.

**Comment by Wyn-Price** [comment] 2017-12-12 22:05
Ok that makes sense. The glass and the door and trapdoor and true rendering are all off the same code. Ill look into it now and see why its not working. Im stilll going to need your help with debugging

**Comment by Wyn-Price** [comment] 2017-12-12 22:12
Does it something about the wrong optifine version in the logs ?

**Comment by kibmcz** [comment] 2017-12-12 22:20
Hmm not 100% sure where to look for that but not seeing anything referencing that.

**Comment by Wyn-Price** [comment] 2017-12-12 22:21
thats fine. I didnt expect anything. Itll be a clear log from SRM so its easy to spot

**Comment by Wyn-Price** [comment] 2017-12-12 22:26
I found out where the issue is, but not why its happening. Im looking into it now

**Comment by Wyn-Price** [comment] 2017-12-12 22:34
Ok i found out why its happening. It was some code i addd while trying to get it to work with C7. The issues with the blocks next to the SRM blocks rendering weirdly should also be fixed. Heres the version:
There are some issues with the switch probe (also mentioned in #207) so ill start that now, but if you could test [this](https://github.com/AbrarSyed/SecretRoomsMod-forge/files/1553535/secretroomsmod-1.12.2-5.1.10.zip) just to make sure it works

**Comment by Wyn-Price** [comment] 2017-12-12 22:39
Ah sorry I uploaded the wrong file. [This ](https://github.com/AbrarSyed/SecretRoomsMod-forge/files/1553553/secretroomsmod-1.12.2-5.1.10.zip) one should work

**Comment by kibmcz** [comment] 2017-12-12 22:46
Hmm on that last one the doors and button rendered in right but there is some odd render glitches going on now.

![2017-12-12_16 44 04](https://user-images.githubusercontent.com/857986/33912559-04476110-df5c-11e7-8fc7-56ae753dd9d9.png)
![2017-12-12_16 44 16](https://user-images.githubusercontent.com/857986/33912567-089c3f1a-df5c-11e7-9c26-82cbd0305fe6.png)
![2017-12-12_16 45 01](https://user-images.githubusercontent.com/857986/33912574-0bd2e166-df5c-11e7-9341-93dde902ae0c.png)

**Comment by Wyn-Price** [comment] 2017-12-12 23:14
Does [this ](https://github.com/AbrarSyed/SecretRoomsMod-forge/files/1553626/secretroomsmod-1.12.2-5.1.10.zip) build work. As for the light block under the door, and the shading issue on the door, Ill do them tommorow as its getting pretty late and I have school tommorow.

**Comment by kibmcz** [comment] 2017-12-12 23:33
The connected textures are still doing that glitchyness (sometimes the ctm connects and sometimes it don't depending on angle), the secret wooden button works but isn't rendering, secret wooden door works but isn't rendering on world load but work fine when removed/and replaced then reloading save.

The secret wooden trap door worked fine on initial world load as was slab rendering working right.

**Comment by Wyn-Price** [comment] 2017-12-12 23:38
So the only issue is the double texture / glitchy thing. I know why that's happening and I'm probably going to remove that part of the code.

**Comment by Wyn-Price** [comment] 2017-12-13 19:18
I think ive solved the double texture issue. Could you just go thorugh and make sure theres still nothing wrong. 
[secretroomsmod-1.12.2-5.1.10.zip](https://github.com/AbrarSyed/SecretRoomsMod-forge/files/1556746/secretroomsmod-1.12.2-5.1.10.zip)

**Comment by kibmcz** [comment] 2017-12-13 19:30
Ok that build does seem pretty solid other than some render glitches. Importantly ctm seems to be working properly :)

1. Secret wooden door and Secret wooden button rendered with no block model on world load but was fine after replacing and reloading world (seems to happen between these builds?)

2. Can see through Secret wooden button from back side when beside a door.
![2017-12-13_13 22 00](https://user-images.githubusercontent.com/857986/33958176-57793fae-e009-11e7-9f26-fda2a1953264.png)

3. Bit of a old one but went from world running the release version and the doors render in half visible (not sure how related)
![2017-12-13_13 23 59](https://user-images.githubusercontent.com/857986/33958327-b2991846-e009-11e7-98ac-4bdd6868a5bf.png)

**Comment by Wyn-Price** [comment] 2017-12-13 19:53
Ok [this](https://github.com/AbrarSyed/SecretRoomsMod-forge/files/1556851/secretroomsmod-1.12.2-5.1.10.zip) build should stop the issue 2. Regarding issue 1, it could be a cause although I doubt it.
 Have you tried closing minecraft then reopening it, that might make a diffrence.

**Comment by kibmcz** [comment] 2017-12-13 20:01
Game crashes as soon as i start looking towards SRM blocks now.

[crash-2017-12-13_14.00.02-client.txt](https://github.com/AbrarSyed/SecretRoomsMod-forge/files/1556892/crash-2017-12-13_14.00.02-client.txt)

**Comment by Wyn-Price** [comment] 2017-12-13 20:03
Ah ok i understand why hold on.

**Comment by Wyn-Price** [comment] 2017-12-13 20:05
is [this](https://github.com/AbrarSyed/SecretRoomsMod-forge/files/1556907/secretroomsmod-1.12.2-5.1.10.zip) build any better?

**Comment by kibmcz** [comment] 2017-12-13 20:08
Still crashes out.

[crash-2017-12-13_14.07.14-client.txt](https://github.com/AbrarSyed/SecretRoomsMod-forge/files/1556918/crash-2017-12-13_14.07.14-client.txt)

**Comment by Wyn-Price** [comment] 2017-12-13 20:12
is [this](https://github.com/AbrarSyed/SecretRoomsMod-forge/files/1556929/secretroomsmod-1.12.2-5.1.10.zip) any better ?

**Comment by kibmcz** [comment] 2017-12-13 20:19
No crash :) 

It looks like #1 and #3 are related to same issue as when i replace the blocks then reload save they render properly.

**Comment by Wyn-Price** [comment] 2017-12-13 20:21
Ok thats good. Did you find any issues with it or is it all ok?

**Comment by kibmcz** [comment] 2017-12-13 20:30
Ok found a bit of a nasty bug. 

With helmet of true sight equipped when you open a door all the SRM blocks within a area render out as normal full block not as the exposed srm block. One way glass even renders  fully as the target full block on both sides. Removing helmet then toggling the door restores the blocks to their proper state.

**Comment by Wyn-Price** [comment] 2017-12-13 20:32
Thats actually funny. As soon as i got the notification about this i commited [this](https://github.com/AbrarSyed/SecretRoomsMod-forge/commit/2c981703b7d39b1cdfa988457dc3d9f18d816839) which fixes it. New build [here](https://github.com/AbrarSyed/SecretRoomsMod-forge/files/1556974/secretroomsmod-1.12.2-5.1.10.zip)

**Comment by kibmcz** [comment] 2017-12-13 20:46
Heh that is funny... anyway helmet all good now. 

Well yea the door/button thing is still present but found something that i'm not sure how its supposed to behave. 
The first plank is a secret gate block
![2017-12-13_14 44 14](https://user-images.githubusercontent.com/857986/33961589-4396ab60-e014-11e7-92d1-0f2da178754f.png)

**Comment by Wyn-Price** [comment] 2017-12-13 20:49
whats the issue with the picture. The secret gate extends 10 blocks in a direction when powered

**Comment by Wyn-Price** [comment] 2017-12-13 20:50
Also have you tried replacing the doors and buttons, I cant replicate it

**Comment by kibmcz** [comment] 2017-12-13 20:51
As per gate thanks i didn't know how it worked thus why i didn't call it a bug.

On the door/button thing it only seems to happen when going between builds and replacing the blocks then reloading world they stay proper.

**Comment by Wyn-Price** [comment] 2017-12-13 20:53
with the going between builds thing, does it still happen when you close Minecraft and reopen it

**Comment by kibmcz** [comment] 2017-12-13 21:05
Yep restarting game causes those blocks to not render.

**Comment by Wyn-Price** [comment] 2017-12-13 21:06
Ok that makes sense. I know why thats happening and I can fix that easily.

**Comment by Wyn-Price** [comment] 2017-12-13 21:11
Hopfully [this](https://github.com/AbrarSyed/SecretRoomsMod-forge/files/1557081/secretroomsmod-1.12.2-5.1.10.zip) should fix those issues

**Comment by kibmcz** [comment] 2017-12-13 21:17
Hmm on trying load world started to load then went to stopping internal server.

[latest.log](https://github.com/AbrarSyed/SecretRoomsMod-forge/files/1557098/latest.log)

**Comment by Wyn-Price** [comment] 2017-12-13 21:20
ok ill try a diffrent technique.

**Comment by Wyn-Price** [comment] 2017-12-13 21:35
could you use [this](https://github.com/AbrarSyed/SecretRoomsMod-forge/files/1557150/secretroomsmod-1.12.2-5.1.10.zip) version, and send me the log, along with the blockpos of the blocks that errored.

**Comment by kibmcz** [comment] 2017-12-13 21:45
Here ya go:
[fml-client-latest.log](https://github.com/AbrarSyed/SecretRoomsMod-forge/files/1557183/fml-client-latest.log)

XYX from f3 debug screen
--------------------------
door: 2479.512 69.00000 268.138
button: 2478.421 70.00000 268.468

Also when the button is replaced by a lever it don't dissapear.

**Comment by Wyn-Price** [comment] 2017-12-13 21:49
is that the position of the door, or the position of the player. Make to look at the right coords. 
![f3lookat](https://user-images.githubusercontent.com/15876682/33964169-71fba628-e04f-11e7-8e11-724a252c7ef0.png)

**Comment by Wyn-Price** [comment] 2017-12-13 21:52
Also if you could do the same with [this](https://github.com/AbrarSyed/SecretRoomsMod-forge/files/1557222/secretroomsmod-1.12.2-5.1.10.zip) that would be helpfull

**Comment by kibmcz** [comment] 2017-12-13 22:15
Ah sorry was use to using the player position here's the results with the latest build using looking at position.

[fml-client-latest.log](https://github.com/AbrarSyed/SecretRoomsMod-forge/files/1557305/fml-client-latest.log)

door: 2479 69 268
button: 2478 70 268

**Comment by Wyn-Price** [comment] 2017-12-13 22:23
could you replace the blocks and close minecraft, then load minecraft again with [this](https://github.com/AbrarSyed/SecretRoomsMod-forge/files/1557327/secretroomsmod-1.12.2-5.1.10.zip) version and send me the log

**Comment by kibmcz** [comment] 2017-12-13 22:32
Here ya go:
[fml-client-latest.log](https://github.com/AbrarSyed/SecretRoomsMod-forge/files/1557347/fml-client-latest.log)

hmm in doing that noticed trap door and its button was not rendering this time

button (for trap door): 2472 69 266
trap door: 2472 68 267

**Comment by Wyn-Price** [comment] 2017-12-13 22:41
For [this](https://github.com/AbrarSyed/SecretRoomsMod-forge/files/1557374/secretroomsmod-1.12.2-5.1.10.zip) version, load it up, place blocks, then quit the game and restart and see if the error occures. Sorry for all these versions, the error is that the mirroredstate isnt being saved to the NBT, and I think I know why.

**Comment by kibmcz** [comment] 2017-12-13 23:34
Ok built up a new test wall with sandstone, one way glass, secret wooden button and secret iron door and it the button/door didn't render on game restart.

**Comment by Wyn-Price** [comment] 2017-12-13 23:40
Could you create a new world and do the same thing with [this](https://github.com/AbrarSyed/SecretRoomsMod-forge/files/1557494/secretroomsmod-1.12.2-5.1.10.zip) version, then send me the log

**Comment by kibmcz** [comment] 2017-12-14 00:08
OK here's the log from a new  world following the requested procedure.
[fml-client-latest.log](https://github.com/AbrarSyed/SecretRoomsMod-forge/files/1557525/fml-client-latest.log)

**Comment by Wyn-Price** [comment] 2017-12-14 00:26
We're there issues loading up the new version?

**Comment by kibmcz** [comment] 2017-12-14 00:37
yep on new version button and the doors are not rendering properly after restart of game

**Comment by Wyn-Price** [comment] 2017-12-14 16:07
does the bug still happen when optifine isnt installed ?

**Comment by Wyn-Price** [comment] 2017-12-14 16:14
Ok ive managed to replicate the issue. Looking more into it now

**Comment by Wyn-Price** [comment] 2017-12-14 17:30
Ok can you test [this](https://github.com/AbrarSyed/SecretRoomsMod-forge/files/1560199/secretroomsmod-1.12.2-5.1.10.zip) and make sure its all good

**Comment by kibmcz** [comment] 2017-12-14 20:30
The doors/buttons didn't render on initial load but rendered every time after replacing the blocks and restarting game. 

Did notice some render glitches/ctm issues.

First off render glitches:
These are random where they appear and the texture goes normal when door opened.
![2017-12-14_14 04 54](https://user-images.githubusercontent.com/857986/34012726-7c5ff4b2-e0da-11e7-8351-2ee9c26e3dd6.png)
![2017-12-14_14 05 03](https://user-images.githubusercontent.com/857986/34012747-935e4dda-e0da-11e7-97ec-b4b4de9d12ba.png)

This one happens after restarting game same every time.
![2017-12-14_14 26 51](https://user-images.githubusercontent.com/857986/34012832-d9a6a49a-e0da-11e7-9d5f-901c982675ba.png)

Secondly is the ctm on the dirt:
![2017-12-14_13 56 13](https://user-images.githubusercontent.com/857986/34012723-74ab88a8-e0da-11e7-9b0c-1ac57db9a387.png)

**Comment by Wyn-Price** [comment] 2017-12-14 20:58
With the grass and dirt, is that somthing CTM does. Also, I cant tell what the problem with the last 2 pics are, could you explain. Ill look more into the CTM issues with pic 1 tommorow. Unfortunately i have to go to school and its getting kinda late.

**Comment by kibmcz** [comment] 2017-12-14 21:30
As per first 2 sandstone ones those are glitchy ctm not connecting on bottom 100% of time  until i trigger the button opened door. The 3rd sandstone shot is the door rendering half as door and half as sandstone full block on game restart this also happened in the new test world.

As per dirt.. it's not blending due to one way glass is doing the same as real glass which greens under the glass block thus showing the green top nature to the front of the block. 

The button thing was due to grass greening before placing button so not issue.

**Comment by Wyn-Price** [comment] 2017-12-14 21:40
I have an idea on how to fix it I'll try tomorrow

**Comment by Wyn-Price** [comment] 2017-12-15 15:36
does [this](https://github.com/AbrarSyed/SecretRoomsMod-forge/files/1563179/secretroomsmod-1.12.2-5.1.10.zip) version work. If it dosnt, does doing f3 + T fix some of the bugs.

**Comment by kibmcz** [comment] 2017-12-15 20:07
Well not seeing any ctm glitching any more also after replacing the dirt blocks  below the one way glass and doing worldedit /green the the dirt wall stayed stealth.

That build looks good so far.

**Comment by Wyn-Price** [comment] 2017-12-15 23:30
So all the errors you found have been fixed? Is there anything that should be fixed before I release this as a version

**Comment by kibmcz** [comment] 2017-12-15 23:50
Looks good for release supporting Optifine C6. 

I'll just have to work out how to work around the Tesselating block model issue with acacia logs on my server map (was fixed on C7).

**Comment by Wyn-Price** [comment] 2017-12-15 23:52
Yeh until the release of the source code for C7 there's nothing I can really do

**Comment by kibmcz** [comment] 2017-12-16 01:42
May have just caught a bug... without optifine installed doors are rendering as full blocks. Didn't catch that until i was sorting out issue on server map and had to remove optifine to prevent crash.

**Comment by Wyn-Price** [comment] 2017-12-16 01:45
Is optifine enabled in the config. BTW for the actual release  not gonna use the config, I'll.mske it detect if optifine I'd enabled.

**Comment by kibmcz** [comment] 2017-12-16 01:47
Ah yea that explains it. So that's switching between two different processing modes to deal with things in the mode vanilla vs optfinee handles things.

Being auto makes sense.

**Comment by Wyn-Price** [comment] 2017-12-16 01:51
I had it in Config so I could test what works with and without optifine but there doesn't seem to be any point in it now. Tommorow I'll make sure there's server compatibility then release the version

**Comment by Wyn-Price** [comment] 2017-12-16 11:59
Ok im making sure the server version works then ill release the version

**Closed** 2017-12-16 12:47 UTC
